# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c74adc9b8307256affe657969338978c3775e97971d79fe7bcf662a14cac109cd2fbb2486931a3a72fc2e8ad6a3149ee419131e0f9acbe51f2b6065abfc7c8e

test:
  secret_key_base: c2cad4f7b1f9b412d19710519bce7804943e48f959aaa24c441c0a3de5b0a462b4da2725d3dcf78fe742d5800b7bdcb081e304f5873041650722bac0b81657b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
